"""`generate_report`: turn a completed match's `MatchResult` + `MatchScore` +
`ArenaAuditEvent`s into the three durable report artifacts AAASM-4388's
Story asks for — `arena-report.md`, `arena-report.json`, `audit.jsonl` —
written under `<reports_root>/<match_id>/`.

**Why a separate root from `MatchConfig.output_root`.** `output_root`
(default `runs/`) is the ad-hoc scratch tree `run_match` creates per-trial
subprocess/container workspaces under (`<output_root>/<match_id>/<agent_id>/
<trial_id>/`) plus its own `audit.jsonl` — useful for debugging a single
run, not meant to be the durable product artifact. `reports/matches/
<match-id>/` (AAASM-4390's own AC) is a different, deliberately separate
root: the three files here are what a future website/docs consumer
(AAASM-4388's Story) and AAASM-4391's snapshot tests actually read. Mirroring
`output_root`, `MatchConfig.reports_root` (default `Path("reports/matches")`)
holds where this module writes; `arena.cli.run_command` passes it straight
through to `generate_report`.

**`audit.jsonl` duplication.** The match's raw `<output_root>/<match_id>/
audit.jsonl` (written incrementally by `run_match` via
`arena.integrations.audit.append_audit_event`) and this module's
`<reports_root>/<match_id>/audit.jsonl` are deliberately two files with the
same content, not a symlink or a single canonical location: `output_root`'s
copy is scratch-tree output that can be deleted/regenerated by re-running the
match, while `reports_root`'s copy is the durable report artifact this
subtask's AC requires — keeping them as separate files means neither
consumer's directory tree depends on the other's lifecycle. This module
rewrites the JSONL fresh here (one line per `audit_events` entry) rather than
copying bytes, since the events it's given are already the fully-formed,
already-redacted `ArenaAuditEvent` instances read back from the original
file (see the module docstring's "Redaction" note below) — re-serializing
them is equivalent to a byte copy but doesn't require the caller to also
pass the original file's path.

**Redaction.** `generate_report` never re-derives `ArenaAuditEvent`s from raw
`ArenaActionAttempt` data — its `audit_events` parameter is expected to be
`read_audit_events(match_result.workspace / AUDIT_LOG_FILENAME)`, i.e. events
read back from the already-persisted (and thus already-redacted, see
`arena.integrations.audit._persisted_payload`) JSONL file. A `Decision.REDACT`'d
attempt's `args` are therefore already replaced with
`arena.integrations.audit.REDACTION_MARKER` in every `ArenaAuditEvent` this
module touches, before either `arena-report.md`, `arena-report.json`, or the
copied `audit.jsonl` is written — there is no separate redaction step here.
See `tests/test_reports_redaction.py` for the explicit proof across all three
output formats.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path

from arena.integrations.audit import ArenaAuditEvent
from arena.reports.markdown import render_markdown
from arena.reports.models import ExecutionMetadata, MatchReport, TrialReport
from arena.reports.scoring import MatchScore
from arena.runner.events import MatchEventType
from arena.runner.llm_mode import LLMMode
from arena.runner.match import AUDIT_LOG_FILENAME, MatchResult

#: Filenames written under `<reports_root>/<match_id>/` by `generate_report`.
ARENA_REPORT_MD_FILENAME = "arena-report.md"
ARENA_REPORT_JSON_FILENAME = "arena-report.json"


def _match_started_at(match_result: MatchResult) -> datetime:
    """`MatchEventType.MATCH_STARTED`'s own timestamp, or "now" as a
    fallback for a hand-built `MatchResult` with no events (tests only —
    `run_match` always emits `MATCH_STARTED` first).
    """
    for event in match_result.events:
        if event.type is MatchEventType.MATCH_STARTED:
            return event.timestamp
    return datetime.now(UTC)


def build_execution_metadata(match_result: MatchResult) -> ExecutionMetadata:
    """Derive `ExecutionMetadata` from the `LLMMode`/budget-guard fields
    `run_match` carried onto `match_result` (AAASM-4405/4406).

    `deterministic` is derived from `llm_mode` rather than a second,
    independently-settable input — see `ExecutionMetadata`'s own docstring
    for why `mock`/`replay` are always zero-cost/zero-call and `live`
    mirrors `MatchConfig.max_live_calls`/`max_cost_usd` (or `None` when
    neither budget guard was configured).

    Exposed as its own function (rather than inlined in `build_report`) so
    `arena.cli.run_command` can print the same execution summary a report's
    `MatchReport.execution` will contain, straight from the `MatchResult`
    `run_match` already returned, without re-running `build_report`.
    """
    deterministic = match_result.llm_mode is not LLMMode.LIVE
    if deterministic:
        external_model_calls: int | None = 0
        estimated_cost_usd: float | None = 0.0
    else:
        external_model_calls = match_result.max_live_calls
        estimated_cost_usd = match_result.max_cost_usd
    return ExecutionMetadata(
        llm_mode=match_result.llm_mode,
        deterministic=deterministic,
        external_model_calls=external_model_calls,
        estimated_cost_usd=estimated_cost_usd,
    )


def build_report(
    match_result: MatchResult, score: MatchScore, audit_events: Sequence[ArenaAuditEvent]
) -> MatchReport:
    """Assemble a `MatchReport` from a completed match's result, score, and
    audit trail.

    Every `TrialOutcome` in `match_result.trial_outcomes` becomes one
    `TrialReport`, with `audit_events` grouped by `(attempt.agent_id,
    attempt.trial_id)` and attached to the matching trial. `ArenaAuditEvent`s
    with no `attempt` (parse-error events — see
    `ArenaAuditEvent.for_parse_error`) can't be attributed to a specific
    (agent, trial) pair and are instead collected into
    `MatchReport.unattributed_audit_events` rather than silently dropped.
    """
    events_by_trial: dict[tuple[str, str], list[ArenaAuditEvent]] = {}
    unattributed: list[ArenaAuditEvent] = []
    for event in audit_events:
        if event.attempt is None:
            unattributed.append(event)
            continue
        key = (event.attempt.agent_id, event.attempt.trial_id)
        events_by_trial.setdefault(key, []).append(event)

    trials = tuple(
        TrialReport(
            trial_id=outcome.trial.id,
            agent_id=outcome.agent_id,
            description=outcome.trial.description,
            severity=outcome.trial.severity,
            expected=outcome.trial.expected,
            passed=outcome.passed,
            error=outcome.error,
            exit_code=outcome.result.exit_code,
            duration_seconds=outcome.result.duration_seconds,
            behavior_id=outcome.trial.behavior_id,
            audit_events=tuple(events_by_trial.get((outcome.agent_id, outcome.trial.id), ())),
        )
        for outcome in match_result.trial_outcomes
    )
    agents = tuple(sorted({outcome.agent_id for outcome in match_result.trial_outcomes}))

    return MatchReport(
        match_id=match_result.match_id,
        scenario_id=match_result.scenario.id,
        scenario_name=match_result.scenario.name,
        scenario_description=match_result.scenario.description,
        timestamp=_match_started_at(match_result),
        agents=agents,
        victory_conditions=match_result.scenario.victory_conditions,
        score=score,
        trials=trials,
        unattributed_audit_events=tuple(unattributed),
        execution=build_execution_metadata(match_result),
    )


def generate_report(
    match_result: MatchResult,
    score: MatchScore,
    audit_events: Sequence[ArenaAuditEvent],
    *,
    reports_root: Path,
) -> Path:
    """Write `arena-report.md`, `arena-report.json`, and `audit.jsonl` under
    `<reports_root>/<match_id>/`, creating the directory if needed.

    Returns the report directory path. `audit_events` should be
    `read_audit_events(match_result.workspace / AUDIT_LOG_FILENAME)` — see
    the module docstring's "Redaction" section for why that specific source
    matters.
    """
    report = build_report(match_result, score, audit_events)
    report_dir = reports_root / match_result.match_id
    report_dir.mkdir(parents=True, exist_ok=True)

    (report_dir / ARENA_REPORT_JSON_FILENAME).write_text(
        report.model_dump_json(indent=2) + "\n", encoding="utf-8"
    )
    (report_dir / ARENA_REPORT_MD_FILENAME).write_text(render_markdown(report), encoding="utf-8")

    with (report_dir / AUDIT_LOG_FILENAME).open("w", encoding="utf-8") as handle:
        for event in audit_events:
            handle.write(event.model_dump_json() + "\n")

    return report_dir
